stages:
  - verify

verify:python:
  stage: verify
  image: python:alpine
  # image: ACCNT.dkr.ecr.us-east-2.amazonaws.com/python:alpine
  tags:
    - python
  script:
    - python --version

verify:terraform:
  stage: verify
  image:
    name: hashicorp/terraform
    entrypoint: [""]
  # image: ACCNT.dkr.ecr.us-east-2.amazonaws.com/hashicorp/terraform:latest
  tags:
    - tf
  script:
    - terraform version
